---
services:
  config:
    version: "0.0.2"

---
spring:
  profile: docker
  cloud:
    config:
      uri: http://config-server:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
